name: Build-KSU-SUSFS_OnePlus_SM8650

on:
  workflow_dispatch:
    inputs:
      manifest_file:
        required: true
        type: choice
        options:
          - gt5pro
          - gt6CommonAce3pro
          - gt6CommonAce5
          - gt6
        default: 'gt6'
      enable_lto:
        description: '启用 Full LTO'
        type: boolean
        default: false
      enable_polly:
        description: '启用 Polly'
        type: boolean
        default: false
      enable_o3:
        description: '启用 O3 优化'
        type: boolean
        default: false
      ksu_type:
        description: '要用的ksu'
        required: true
        type: choice
        options:
          - ksun
          - mksu
          - SukiUltra
        default: 'SukiUltra'
      BUILD_METHOD:
        type: choice
        description: "编译方式"
        required: true
        default: gki
        options:
          - gki
          - perf
      CPUD:
        description: "处理器代号"
        required: true
        default: 'pineapple'
      SUSFS_CI:
        description: "SUSFS模块下载？"
        required: true
        type: choice
        options:
          - CI
          - Realse
          - NO
        default: 'CI'
      KPM:
        type: boolean
        description: "是否启用KPM？"
        required: true
        default: true
      KERNEL_NAME:
        description: "修改内核名称"
        required: true
        default: '-android14-11-o-g4c9c8979e2a7'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - uses: actions/setup-python@main
        with:
          python-version: "3.x"

      - name: Install dependencies and Clang 19
        run: |
         # echo "CT=v$(date +%Y%m%d)" >> $GITHUB_ENV
         echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
         sudo apt-get update
         sudo apt-get install -y repo git curl patch lld
         sudo bash -c "echo 'deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-19 main' > /etc/apt/sources.list.d/llvm.list"
         sudo bash -c "echo 'deb-src http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-19 main' >> /etc/apt/sources.list.d/llvm.list"
         wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
         sudo apt-get update
         sudo apt-get install -y clang-19 lld-19 llvm-19
         mkdir kernel_workspace

      - name: Show selected inputs debug
        run: |

          echo "Selected manifest_file: ${{ github.event.inputs.manifest_file }}"
          echo "Selected enable_lto: ${{ github.event.inputs.enable_lto }}"
          echo "Selected enable_polly: ${{ github.event.inputs.enable_polly }}"
          echo "Selected enable_o3: ${{ github.event.inputs.enable_o3 }}"
          echo "Selected ksu_type: ${{ github.event.inputs.ksu_type }}"
          echo "Selected BUILD_METHOD: ${{ github.event.inputs.BUILD_METHOD }}"
          echo "Selected CPUD: ${{ github.event.inputs.CPUD }}"
          echo "Selected SUSFS_CI: ${{ github.event.inputs.SUSFS_CI }}"
          echo "Selected KPM: ${{ github.event.inputs.KPM }}"
          echo "Selected KERNEL_NAME: ${{ github.event.inputs.KERNEL_NAME }}"
          
      - name: Map friendly name to manifest file
        id: map_manifest
        run: |
          case "${{ github.event.inputs.manifest_file }}" in
            "gt5pro") manifest="gt5pro" ;;
            "gt6CommonAce3pro") manifest="gt6CommonAce3pro" ;;
            "gt6CommonAce5") manifest="gt6CommonAce5" ;;
            "gt6") manifest="gt6" ;;
          esac
          echo "mapped_manifest=$manifest" >> $GITHUB_OUTPUT

      - name: Initialize repo and sync
        working-directory: kernel_workspace
        run: |
          repo init -u https://github.com/Carl1984/kernel_manifest.git -b realme/sm8650 -m ${{ steps.map_manifest.outputs.mapped_manifest }}.xml --depth=1
          repo --trace sync -c -j$(nproc) --no-tags --fail-fast

      - name: Build Kernel
        working-directory: kernel_workspace
        id: build
        run: | 
         curl -Ls https://raw.githubusercontent.com/Carl1984/kernel_manifest/refs/heads/realme/sm8650/build_shell/build_${{ github.event.inputs.ksu_type }}_sm8650.sh -o build_${{ github.event.inputs.ksu_type }}_sm8650.sh
         chmod +x build_${{ github.event.inputs.ksu_type }}_sm8650.sh
         ./build_${{ github.event.inputs.ksu_type }}_sm8650.sh ${{ steps.map_manifest.outputs.mapped_manifest }} \
                                ${{ github.event.inputs.enable_lto }} \
                                ${{ github.event.inputs.enable_polly }} \
                                ${{ github.event.inputs.enable_o3 }}  \
                                ${{ github.event.inputs.KERNEL_NAME }} \


      - name: Make AnyKernel3 for ksun and mksu
        if: ${{ github.event.inputs.ksu_type == 'ksun' || github.event.inputs.ksu_type == 'mksu' }}
        run: |
         git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
         rm -rf ./AnyKernel3/.git
         cp kernel_workspace/kernel_platform/out/msm-kernel-pineapple-gki/dist/Image ./AnyKernel3/
         

      - name: Make AnyKernel3 for SukiUltra
        if: ${{ github.event.inputs.ksu_type == 'SukiUltra' }}
        run: |
          git clone https://github.com/Numbersf/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git

          dir1="kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.BUILD_METHOD }}/dist/"
          dir2="kernel_workspace/kernel_platform/bazel-out/k8-fastbuild/bin/msm-kernel/${{ github.event.inputs.CPUD }}_gki_kbuild_mixed_tree/"
          dir3="kernel_workspace/kernel_platform/out/msm-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.BUILD_METHOD }}/dist/"
          dir4="kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.BUILD_METHOD }}/gki_kernel/common/arch/arm64/boot/"
          dir5="kernel_workspace/kernel_platform/out/msm-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.BUILD_METHOD }}/gki_kernel/common/arch/arm64/boot/"
          target1="./AnyKernel3/"
          target2="./kernel_workspace/kernel"

          # 查找 Image 文件
          if find "$dir1" -name "Image" | grep -q "Image"; then
            image_path="$dir1"Image
          elif find "$dir2" -name "Image" | grep -q "Image"; then
            image_path="$dir2"Image
          elif find "$dir3" -name "Image" | grep -q "Image"; then
            image_path="$dir3"Image
          elif find "$dir4" -name "Image" | grep -q "Image"; then
            image_path="$dir4"Image
          elif find "$dir5" -name "Image" | grep -q "Image"; then
            image_path="$dir5"Image
          else
            image_path=$(find "./kernel_workspace/kernel_platform/common/out/" -name "Image" | head -n 1)
          fi

          # 拷贝 Image
          if [ -n "$image_path" ] && [ -f "$image_path" ]; then
            mkdir -p "$dir1"
            if [ "$(realpath "$image_path")" != "$(realpath "$dir1"Image)" ]; then
              cp "$image_path" "$dir1"
            else
              echo "源文件与目标相同，跳过复制"
            fi
            cp "$dir1"Image ./AnyKernel3/Image
          else
            echo "未找到 Image 文件，构建可能失败"
            exit 1
          fi



      - name: Apply patch_linux and replace Image
        if: ${{github.event.inputs.ksu_type == 'SukiUltra' && github.event.inputs.KPM == 'true' }}
        run: |
          cd /home/runner/work/kernel_manifest/kernel_manifest/kernel_workspace/kernel_platform/out/msm-kernel-${{ github.event.inputs.CPUD }}-${{ github.event.inputs.BUILD_METHOD }}/dist
          # curl -LO https://raw.githubusercontent.com/Numbersf/Action-Build/main/patch_linux
          curl -LO https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.11-beta/patch_linux
          chmod +x patch_linux
          ./patch_linux
          rm -f Image
          mv oImage Image
          cp Image $GITHUB_WORKSPACE/AnyKernel3/Image

      # 下载 SUSFS 模块（CI）
      - name: Download Latest SUSFS Module from CI
        if: ${{github.event.inputs.ksu_type == 'SukiUltra' && github.event.inputs.SUSFS_CI == 'CI' }}
        run: |
          LATEST_RUN_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/sidex15/susfs4ksu-module/actions/runs?status=success" | \
            jq -r '.workflow_runs[] | select(.head_branch == "v1.5.2+") | .id' | head -n 1)

          if [ -z "$LATEST_RUN_ID" ]; then
            echo "No successful run found for branch v1.5.2+"
            exit 1
          fi

          ARTIFACT_URL=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/sidex15/susfs4ksu-module/actions/runs/$LATEST_RUN_ID/artifacts" | jq -r '.artifacts[0].archive_download_url')

          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o ksu_module_susfs_1.5.2+_CI.zip "$ARTIFACT_URL"
          cp ksu_module_susfs_1.5.2+_CI.zip ./AnyKernel3/

      # 下载 SUSFS 模块（Release）
      - name: Download Latest SUSFS Module from Release
        if: ${{github.event.inputs.ksu_type == 'SukiUltra' &&  github.event.inputs.SUSFS_CI == 'Realse' }}
        run: |
          wget https://github.com/sidex15/ksu_module_susfs/releases/latest/download/ksu_module_susfs_1.5.2+.zip
          cp ksu_module_susfs_1.5.2+.zip ./AnyKernel3/


      - name: Upload AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_-${{ steps.map_manifest.outputs.mapped_manifest }}-${{ steps.build.outputs.kernel_version }}-${{ github.event.inputs.ksu_type }}-${{ steps.build.outputs.ksu_version }}-SUSFS-${{ steps.build.outputs.susfs_version }}-${{ env.BUILD_TIME }}
          path: ./AnyKernel3/*

      - name: 创建发布
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name:  "${{ github.event.inputs.ksu_type }}_${{ github.event.inputs.manifest_file }}_${{ steps.build.outputs.ksu_version }}_${{ env.BUILD_TIME }}"
          name: "Realme_${{ github.event.inputs.manifest_file }} Build ${{ github.run_number }}_${{ env.BUILD_TIME }}"
          body: |
            编译 ${{ github.event.inputs.ksu_type }} 内核
            - 机型： Realme-${{ github.event.inputs.manifest_file }}
            - 特性： MKSU+SUSFS+VFS
            - KPM：  ${{ github.event.inputs.KPM }}
            - 编译时间： ${{ env.BUILD_TIME }}
            - KSU版本： ${{ steps.build.outputs.ksu_version }}
            - SUSFS： ${{ steps.build.outputs.susfs_version }}
            - 内核版本: ${{ steps.build.outputs.kernel_version }}${{ github.event.inputs.KERNEL_NAME }}        
            - LZ4，ZSTD
            - KSU Next 管理器：[KernelSU-Next](https://github.com/KernelSU-Next/KernelSU-Next/releases)
            - SukiSU 管理器：[SukiSU-Ultra](https://github.com/ShirkNeko/SukiSU-Ultra/releases)
            - MKSU 管理器：：[MKSU Action](https://github.com/5ec1cff/KernelSU/actions/workflows/build-manager.yml)


          draft: false
          prerelease: false


